name: Create issue based on condition

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create issue if condition is false
        if: ${{ !eq(1, 2) }}
        run: |
          # Create an issue using the GitHub API
          gh issue create --title "Issue created based on condition" --body "This issue was created because the condition (1=2) is false."
