name: Create issue based on condition

on:
  push:
    branches:
      - main

jobs:
  check-condition:
    runs-on: ubuntu-latest

    steps:
      - name: Check condition
        run: |
          #!/bin/bash
          # Check if the condition (1=2) is false
          if [ "1" != "2" ]; then
            echo "true"
          else
            echo "false"
          fi

  evaluate-condition:
    runs-on: ubuntu-latest
    needs: check-condition

    steps:
      - name: Evaluate condition expression
        id: evaluate-condition
        run: |
          #!/bin/bash

          # Get the result of the check-condition step
          condition_result=${{ steps.check-condition.outputs.result }}

          # Check if the condition is false
          if [ "${condition_result}" == "true" ]; then
            echo "The condition is false."
          else
            echo "The condition is true."
          fi

  create-issue:
    runs-on: ubuntu-latest
    needs: evaluate-condition

    steps:
      - name: Create issue if condition is false
        if: ${{ steps.evaluate-condition.outputs.condition_result == 'true' }}
        run: |
          # Create an issue using the GitHub API
          gh issue create --title "Issue created based on condition" --body "This issue was created because the condition (1=2) is false."
